#!/bin/bash

clean-repo(){
  git clean -df
  sudo find . -name "target" -type d -exec rm -rf {} \; | true
}

set -e
set -x

echo "___________________________________________"
echo "HOPS-GPU-MANAGEMENT"
cd ~/code/hops/hops-gpu-management
clean-repo

echo "___________________________________________"
echo "HOPS-GPU-MANAGEMENT-IMPL-NVIDIA"
cd ~/code/hops/hops-gpu-management-impl-nvidia
clean-repo

echo "___________________________________________"
echo "HOPS-GPU-MANAGEMENT-IMPL-AMD"
cd ~/code/hops/hops-gpu-management-impl-amd
clean-repo

echo "___________________________________________"
echo "HOPS-METADATA-DAL"
cd ~/code/hops/hops-metadata-dal
clean-repo

echo "___________________________________________"
echo "HOPS-METADATA-DAL-IMPL-NDB"
cd ~/code/hops/hops-metadata-dal-impl-ndb
clean-repo

echo "___________________________________________"
echo "HOPS"
cd ~/code/hops/hops
clean-repo

exit 0
