#!/bin/bash

if [ ! "$#" -eq 2 ]; then
    echo "Please enter {remote} and {branch name} i.e., ./cmd salman master"
    exit 1
fi

remote=$1
branch=$1/$2

clean-repo(){
  git clean -df
  sudo find . -name "target" -type d -exec rm -rf {} \; | true
}

set -e
set -x

noCommits=2

echo "___________________________________________"
echo "HOPS-GPU-MANAGEMENT"
cd ~/code/hops/hops-gpu-management
clean-repo
git pull
echo "Last $noCommits commit(s)"
git log -n $noCommits
mvn clean install -DskipTests   

echo "___________________________________________"
echo "HOPS-GPU-MANAGEMENT-IMPL-NVIDIA"
cd ~/code/hops/hops-gpu-management-impl-nvidia
clean-repo
git pull
mvn clean install -DskipTests   

echo "___________________________________________"
echo "HOPS-GPU-MANAGEMENT-IMPL-AMD"
cd ~/code/hops/hops-gpu-management-impl-amd
clean-repo
git pull
mvn clean install -DskipTests   

echo "___________________________________________"
echo "HOPS-METADATA-DAL"
cd ~/code/hops/hops-metadata-dal
clean-repo
git fetch $remote
git checkout $branch
mvn clean install -DskipTests   

echo "___________________________________________"
echo "HOPS-METADATA-DAL-IMPL-NDB"
cd ~/code/hops/hops-metadata-dal-impl-ndb
clean-repo
git fetch $remote
git checkout $branch
mvn clean install -DskipTests   

echo "___________________________________________"
echo "HOPS"
cd ~/code/hops/hops
clean-repo
git fetch $remote
git checkout $branch
mvn clean generate-resources install -Pnative,dist -Dmaven.javadoc.skip=true -nsu -DskipTests
mvn test-compile

cd ~/code/hops/hops-metadata-dal-impl-ndb/src/main/resources
cp ndb-config.properties.template ndb-config.properties
sed -i "s#com.mysql.clusterj.connectstring.*#com.mysql.clusterj.connectstring=localhost#g" ndb-config.properties
sed -i "s#com.mysql.clusterj.database.*#com.mysql.clusterj.database=hop_salman#g" ndb-config.properties
sed -i "s#io.hops.metadata.ndb.mysqlserver.host.*#io.hops.metadata.ndb.mysqlserver.host=localhost#g" ndb-config.properties
sed -i "s#io.hops.metadata.ndb.mysqlserver.username.*#io.hops.metadata.ndb.mysqlserver.username=hop#g" ndb-config.properties
sed -i "s#io.hops.metadata.ndb.mysqlserver.password.*#io.hops.metadata.ndb.mysqlserver.password=hop#g" ndb-config.properties

cd ~/code/hops/hops-metadata-dal-impl-ndb/schema
mysql -uhop -phop -hlocalhost -P3306 --protocol=TCP -f -e "DROP DATABASE IF EXISTS hop_salman" | true
mysql -uhop -phop -hlocalhost -P3306 --protocol=TCP -f -e "ALTER TABLESPACE ts_1 drop datafile 'ts_1_data_file_0.dat' ENGINE ndbcluster" | true
mysql -uhop -phop -hlocalhost -P3306 --protocol=TCP -f -e "DROP TABLESPACE ts_1 ENGINE ndbcluster" | true
mysql -uhop -phop -hlocalhost -P3306 --protocol=TCP -f -e "DROP LOGFILE GROUP lg_1 ENGINE ndbcluster" | true
mysql -uhop -phop -hlocalhost -P3306 --protocol=TCP -f -e "CREATE DATABASE hop_salman"  | true
source ./create-tables.sh localhost 3306 hop hop hop_salman

exit 0


