#!/bin/bash

if [ ! "$#" -eq 1 ]; then
    echo "Please enter unit test name "
    exit 1
fi

unittest=$1

cd ~/code/hops/hops
#mvn -Pndb test -Dtest=$unittest  > /tmp/errors 2>&1
export AWS_CREDENTIAL_PROFILES_FILE="/home/vagrant/.aws/file"
mvn -o -Pndb surefire:test -Dtest=$unittest -DfailIfNoTests=false > /tmp/errors 2>&1

retval=$?

exit $retval



