#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ ! "$#" -eq 4 ]; then
    echo "Missing params. Example ./run-all-unit-tests {user} {hostname} {output-dir} {failed-test-retry-count}"
    exit 1
fi

user=$1
mastermachine=$2
outputdir=$3
maxretry=$4
port=8888
thismachine=$(hostname)

if [ "$maxretry" -lt "1" ]; then
    echo "Retry count can not be less than 1"
    exit 1
fi

while true;
do
  unittest=$(beanstalkd-cli --server $mastermachine --port $port pop --tube testing)
  
  if [ -z "$unittest" ]; then
    sleep 1
    echo "Waiting for tests"
    continue
  fi

  counter=0
  start=`date +%s`

  while [ $counter -lt $maxretry ]; do
    killall java
    echo "Running $unittest"
    $DIR/run-unit-test $unittest
    retval=$?
    echo "Finished $unittest . Return value $retval"
    let counter+=1
    if [ "$retval" -eq 0 ]; then
      break;
    fi
  done
  
  end=`date +%s`
  runtime=$((end-start))
  timestamp=$(date)

  ssh $user@$mastermachine "mkdir -p $outputdir"

  if [ "$retval" -eq 0 ]; then
      echo "Test Passed"
      ssh $user@$mastermachine "echo -e 'Pass\tRanOn: $thismachine\t$TS: $timestamp\tDuration: $runtime sec\tRetry: $counter\t$unittest' >> $outputdir/results.txt"
  else
      echo "Test Failed"
      pushd .
      cd ~/code/hops/hops
      TestNameSimple=`echo $unittest | sed 's/.java//g'`
      FullPath=`find . -iname "*$TestNameSimple-output.txt"`
      if [ -n "$FullPath" ]; then
        ssh $user@$mastermachine "echo -e 'FAIL\tRanOn: $thismachine\t$TS: $timestamp\tDuration: $runtime sec\tRetry: $counter\t$unittest' >> $outputdir/results.txt"
        scp $FullPath "$user@$mastermachine:$outputdir/$unittest.txt"
      fi
      popd
  fi
done 

exit 0


