#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ ! "$#" -eq 4 ]; then
    echo "Missing params. Example ./run-all-unit-tests {user} {hostname} {output-dir} {failed-test-retry-count}"
    exit 1
fi

user=$1
mastermachine=$2
outputdir=$3
maxretry=$4
port=8888
thismachine=$(hostname)

if [ "$maxretry" -lt "1" ]; then
    echo "Retry count can not be less than 1"
    exit 1
fi

while true;
do
  unittest=$(beanstalkd-cli --server $mastermachine --port $port pop --tube testing)
  
  if [ -z "$unittest" ]; then
    sleep 1
    echo "Waiting for tests"
    continue
  fi

  counter=0
  start=`date +%s`

  while [ $counter -lt $maxretry ]; do
    killall java
    echo "Running $unittest"
    $DIR/run-unit-test $unittest
    retval=$?
    echo "Finished $unittest . Return value $retval"
    let counter+=1
    if [ "$retval" -eq 0 ]; then
      break;
    fi
  done
  
  end=`date +%s`
  runtime=$((end-start))
  timestamp=$(date +'%B-%d-Time-%H-%M')

  ssh $user@$mastermachine "mkdir -p $outputdir"

  if [ "$retval" -eq 0 ]; then
      echo "Test Passed"
      ssh $user@$mastermachine "printf 'Pass RanOn: %-9s TS: %-20s Duration: %-5s Retry: %-3s  %s\n' $thismachine $timestamp $runtime $counter $unittest >> $outputdir/results.txt"
  else
      echo "Test Failed"
      ssh $user@$mastermachine "printf 'FAIL RanOn: %-9s TS: %-20s Duration: %-5s Retry: %-3s  %s\n' $thismachine $timestamp $runtime $counter $unittest >> $outputdir/results.txt"
  fi
  
  pushd .
  cd ~/code/hops/hops

  FullPath=`find . -iname "*$unittest.*txt"`
  if [ -n "$FullPath" ]; then
    scp $FullPath "$user@$mastermachine:$outputdir/$unittest.txt"
  fi

  FullPath=`find . -iname "*$unittest-output.*txt"`
  if [ -n "$FullPath" ]; then
    scp $FullPath "$user@$mastermachine:$outputdir/$unittest-output.txt"
  fi

  #copy test xml file
  FullPath=`find . -iname "Test-*$unittest.*xml"`
  if [ -n "$FullPath" ]; then
    scp $FullPath "$user@$mastermachine:$outputdir/Test-$unittest.xml"
  fi
  popd
  
done 

exit 0


