#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

user=vagrant
mastermachine=localhost
outputdir=/home/vagrant/test-results
port=8888
thismachine=$(hostname)

while true;
do
  unittest=$(beanstalkd-cli --server $mastermachine --port $port pop --tube testing)
  
  if [ -z "$unittest" ]; then
    sleep 1
    echo "Test not found"
    continue
  fi

  killall java
  echo "Running $unittest"
  $DIR/run-unit-test $unittest
  retval=$?
  echo "Finished $unittest"

  ssh $user@$mastermachine "mkdir -p $outputdir"

  if [ "$retval" -eq 0 ]; then
      echo "Test Passed"
      ssh $user@$mastermachine "echo 'Pass    $unittest\t\t\t\tRanOn: $thismachine' > $outputdir/results.txt"
  else
      echo "Test Failed"
      pushd .
      cd ~/code/hops/hops
      TestNameSimple=`echo $unittest | sed 's/.java//g'`
      FullPath=`find . -iname "*$TestNameSimple-output.txt"`
      if [ -n "$FullPath" ]; then
        ssh $user@$mastermachine "echo 'FAILED    $unittest\t\t\t\tRanOn: $thismachine' > $outputdir/results.txt"
        scp $FullPath $user@$mastermachine:$outputdir/
      fi
      popd
  fi
done 

exit 0


